# Generated by Django 4.2.27 on 2026-01-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="credits",
            field=models.IntegerField(default=5, help_text="Number of resumes user can generate"),
        ),
    ]
