# Generated by Django 4.2.27 on 2026-01-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_credits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="credits",
        ),
        migrations.AddField(
            model_name="user",
            name="resume_credits",
            field=models.IntegerField(default=0, help_text="Number of resumes user can generate"),
        ),
    ]
