# Generated by Django 4.2.27 on 2026-01-13 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_credits_user_resume_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_name",
            field=models.CharField(
                blank=True, default="", help_text="Telegram display name", max_length=40
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True, default="", help_text="Telegram username", max_length=40, unique=True
            ),
        ),
    ]
