# Generated by Django 4.2.29 on 2026-04-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_user_name_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_regions",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of preferred region slugs (empty = all regions)",
            ),
        ),
    ]
