# Generated by Django 4.2.29 on 2026-04-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_preferred_regions"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="weekly_ai_calls",
            field=models.IntegerField(default=0, help_text="AI generation calls used this week"),
        ),
        migrations.AddField(
            model_name="user",
            name="weekly_ai_calls_reset",
            field=models.DateTimeField(
                blank=True, help_text="When the weekly AI call counter was last reset", null=True
            ),
        ),
    ]
