# Generated by Django 4.2.29 on 2026-04-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="APICallLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("fireworks", "Fireworks AI")],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("endpoint", models.CharField(max_length=255)),
                ("tokens_used", models.IntegerField(default=0)),
                ("cost", models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ("response_time_ms", models.IntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "created_at"], name="analytics_a_provide_64e250_idx"
                    )
                ],
            },
        ),
    ]
