# Generated by Django 4.2.29 on 2026-04-09 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[("job_feed_scroll", "Job Feed Scroll")],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("telegram_id", models.BigIntegerField(db_index=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"], name="analytics_u_event_t_2fabd2_idx"
                    )
                ],
            },
        ),
    ]
