# Generated by Django 4.2.29 on 2026-03-28 08:49

import uuid

import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("matching", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapeState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("channel_username", models.CharField(max_length=100, unique=True)),
                ("last_message_id", models.PositiveIntegerField(default=0)),
                ("last_scraped_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "scrape_state",
            },
        ),
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("company", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField()),
                ("salary_min", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_max", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_currency", models.CharField(blank=True, default="", max_length=10)),
                (
                    "employment_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "work_format",
                    models.CharField(
                        blank=True,
                        choices=[("office", "Office"), ("remote", "Remote"), ("hybrid", "Hybrid")],
                        default="",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("experience_years", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("skills", models.JSONField(blank=True, default=list)),
                ("contact_info", models.CharField(blank=True, default="", max_length=500)),
                ("language", models.CharField(blank=True, default="", max_length=10)),
                (
                    "source",
                    models.CharField(
                        choices=[("telegram", "Telegram"), ("manual", "Manual"), ("api", "API")],
                        default="telegram",
                        max_length=20,
                    ),
                ),
                ("source_channel", models.CharField(blank=True, default="", max_length=100)),
                ("source_message_id", models.PositiveIntegerField(blank=True, null=True)),
                ("source_url", models.URLField(blank=True, default="", max_length=500)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "embedding",
                    pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "vacancies",
                "ordering": ["-posted_at", "-created_at"],
                "indexes": [
                    models.Index(fields=["company"], name="vacancies_company_5067b3_idx"),
                    models.Index(fields=["created_at"], name="vacancies_created_7d7ee7_idx"),
                    models.Index(fields=["source_channel"], name="vacancies_source__c294d3_idx"),
                    models.Index(fields=["posted_at"], name="vacancies_posted__42aaba_idx"),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="vacancy_embedding_hnsw_idx",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="vacancy",
            constraint=models.UniqueConstraint(
                fields=("source_channel", "source_message_id"), name="unique_channel_message"
            ),
        ),
    ]
