# Generated by Django 4.2.29 on 2026-04-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="region",
            field=models.CharField(blank=True, db_index=True, default="", max_length=30),
        ),
    ]
