# Generated by Django 4.2.29 on 2026-04-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vacancies", "0002_vacancy_region"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="country",
            field=models.CharField(blank=True, db_index=True, default="UZ", max_length=2),
        ),
    ]
