# Generated by Django 4.2.27 on 2025-12-22 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("promocodes", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="promocode",
            new_name="promocodes_code_df9561_idx",
            old_name="promocodes_code_idx",
        ),
        migrations.RenameIndex(
            model_name="promocode",
            new_name="promocodes_is_acti_fc63ba_idx",
            old_name="promocodes_is_active_idx",
        ),
        migrations.RenameIndex(
            model_name="promocodeusage",
            new_name="promocode_u_user_id_803052_idx",
            old_name="promocode_u_user_id_code_idx",
        ),
        migrations.RenameIndex(
            model_name="promocodeusage",
            new_name="promocode_u_code_ac991e_idx",
            old_name="promocode_u_code_idx",
        ),
    ]
