# Generated by Django 4.2.8 on 2025-12-13 06:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_user_id_8d58fd_idx",
            old_name="subscripti_user_id_status_idx",
        ),
        migrations.RenameIndex(
            model_name="subscription",
            new_name="subscriptio_status_572d44_idx",
            old_name="subscripti_status_idx",
        ),
    ]
