# Generated by Django 4.2.27 on 2026-01-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "subscriptions",
            "0002_rename_subscripti_user_id_status_idx_subscriptio_user_id_8d58fd_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="credits",
            field=models.IntegerField(
                default=0, help_text="Number of resumes user can generate with this plan"
            ),
        ),
    ]
