# Generated by Django 4.2.27 on 2026-01-08 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0003_subscriptionplan_credits"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="resume_credits",
            field=models.IntegerField(
                default=0, help_text="Number of resumes user can generate with this subscription"
            ),
        ),
    ]
