# Generated by Django 4.2.27 on 2026-01-08 07:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0004_subscription_resume_credits"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subscriptionplan",
            old_name="credits",
            new_name="resume_credits",
        ),
    ]
