# Generated by Django 4.2.27 on 2026-01-08 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("subscriptions", "0005_rename_credits_subscriptionplan_resume_credits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="resume_credits",
        ),
    ]
