# Generated by Django 4.2.27 on 2026-01-01 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        blank=True,
                        help_text="Job position this question is for (null for generic questions)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("personal", "Personal Information"),
                            ("professional", "Professional"),
                            ("education", "Education"),
                            ("skills", "Skills"),
                            ("position_specific", "Position Specific"),
                            ("other", "Other"),
                        ],
                        default="professional",
                        help_text="Question category",
                        max_length=50,
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Field name for mapping to resume data (e.g., 'experience', 'skills')",
                        max_length=100,
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True, help_text="Whether this question must be answered"
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="Display order within position/category"
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("multi", "Multiple Choice"),
                            ("file", "File Upload"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional metadata (e.g., options for multi-choice)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "questions",
                "ordering": ["order", "position", "category"],
            },
        ),
        migrations.CreateModel(
            name="QuestionTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("ru", "Russian"),
                            ("uz", "Uzbek"),
                            ("uz2", "Ozbek"),
                        ],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("text", models.TextField(help_text="Question text in this language")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "db_table": "question_translations",
            },
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["position", "category"], name="questions_positio_b0468d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["category"], name="questions_categor_3ee678_idx"),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(fields=["order"], name="questions_order_2c3df8_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="question",
            unique_together={("position", "field_name", "order")},
        ),
        migrations.AddIndex(
            model_name="questiontranslation",
            index=models.Index(
                fields=["question", "language"], name="question_tr_questio_3d941c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="questiontranslation",
            index=models.Index(fields=["language"], name="question_tr_languag_985cdb_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="questiontranslation",
            unique_together={("question", "language")},
        ),
    ]
