# Generated by Django 4.2.27 on 2026-01-07 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("credits", models.IntegerField(unique=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="UZS", max_length=3)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "credit_packages",
                "ordering": ["credits"],
            },
        ),
        migrations.CreateModel(
            name="CreditTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("purchase", "Purchase"),
                            ("usage", "Usage"),
                            ("refund", "Refund"),
                            ("bonus", "Bonus"),
                            ("admin_adjustment", "Admin Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("credits", models.IntegerField(help_text="Positive for add, negative for deduct")),
                (
                    "balance_after",
                    models.IntegerField(help_text="User's balance after this transaction"),
                ),
                (
                    "amount_paid",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
                ),
                ("currency", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "payment_provider",
                    models.CharField(
                        default="click",
                        help_text="Payment provider used (click, payme, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "payment_id",
                    models.CharField(
                        blank=True,
                        help_text="External payment provider transaction ID",
                        max_length=255,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "resume_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Resume ID if credits used for resume generation",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True, help_text="Admin notes or error messages")),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional data (invoice payload, etc.)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "package",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="store.creditpackage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "credit_transactions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("provider", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("processed", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "transaction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhooks",
                        to="store.credittransaction",
                    ),
                ),
            ],
            options={
                "db_table": "payment_webhooks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["user", "-created_at"], name="credit_tran_user_id_c82af7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(fields=["payment_id"], name="credit_tran_payment_7cd36b_idx"),
        ),
        migrations.AddIndex(
            model_name="credittransaction",
            index=models.Index(
                fields=["transaction_type", "status"], name="credit_tran_transac_8a5e43_idx"
            ),
        ),
    ]
