# Generated by Django 4.2.27 on 2025-12-24 09:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(help_text="Resume title", max_length=255)),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded resume file", upload_to="resumes/%Y/%m/%d/"
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.BigIntegerField(help_text="File size in bytes")),
                ("content_type", models.CharField(max_length=50)),
                (
                    "meta",
                    models.JSONField(
                        blank=True, default=dict, help_text="Parsed form fields and resume metadata"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processed", "Processed"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resumes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResumeSocialLink",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("platform", models.CharField(help_text="e.g., LinkedIn, GitHub", max_length=100)),
                ("url", models.URLField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_links",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "db_table": "resume_social_links",
            },
        ),
        migrations.CreateModel(
            name="ResumeSkill",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.CharField(help_text="e.g., Programming, Soft Skills", max_length=255),
                ),
                ("skill_tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "db_table": "resume_skills",
            },
        ),
        migrations.CreateModel(
            name="ResumeProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("technologies", models.JSONField(blank=True, default=list)),
                ("start_date", models.CharField(max_length=20)),
                ("end_date", models.CharField(blank=True, max_length=20, null=True)),
                ("currently", models.BooleanField(default=False)),
                ("responsibilities", models.JSONField(blank=True, default=list)),
                ("achievements", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "db_table": "resume_projects",
            },
        ),
        migrations.CreateModel(
            name="ResumeExperience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("JOB", "Job"), ("INTERNSHIP", "Internship"), ("OTHER", "Other")],
                        default="JOB",
                        max_length=20,
                    ),
                ),
                ("company", models.CharField(max_length=255)),
                ("position", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, default="", max_length=255)),
                ("start_date", models.CharField(help_text="YYYY-MM or YYYY-MM-DD", max_length=20)),
                ("end_date", models.CharField(blank=True, max_length=20, null=True)),
                ("currently", models.BooleanField(default=False)),
                ("responsibilities", models.JSONField(blank=True, default=list)),
                ("achievements", models.JSONField(blank=True, default=list)),
                ("skill_tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiences",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "db_table": "resume_experiences",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ResumeEducation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("institution", models.CharField(max_length=255)),
                ("degree", models.CharField(max_length=255)),
                ("study_field", models.CharField(max_length=255)),
                ("start_date", models.CharField(max_length=20)),
                ("end_date", models.CharField(blank=True, max_length=20, null=True)),
                ("currently", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "db_table": "resume_educations",
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(fields=["user", "created_at"], name="resumes_user_id_ee2424_idx"),
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(fields=["user", "deleted"], name="resumes_user_id_4e9b43_idx"),
        ),
    ]
