# Generated by Django 4.2.27 on 2026-01-02 12:09

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resumeeducation",
            old_name="currently",
            new_name="current",
        ),
        migrations.RenameField(
            model_name="resumeexperience",
            old_name="currently",
            new_name="current",
        ),
        migrations.RenameField(
            model_name="resumeproject",
            old_name="currently",
            new_name="current",
        ),
        migrations.RenameField(
            model_name="resumeproject",
            old_name="technologies",
            new_name="skills_used",
        ),
        migrations.RenameField(
            model_name="resumesociallink",
            old_name="platform",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="resumeeducation",
            name="study_field",
        ),
        migrations.RemoveField(
            model_name="resumeproject",
            name="title",
        ),
        migrations.RemoveField(
            model_name="resumeskill",
            name="category",
        ),
        migrations.RemoveField(
            model_name="resumeskill",
            name="skill_tags",
        ),
        migrations.AddField(
            model_name="resume",
            name="email",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="resume",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="resume",
            name="location",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="resume",
            name="phone",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="resume",
            name="position",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="resume",
            name="professional_summary",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="resumeeducation",
            name="achievements",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resumeeducation",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="resumeeducation",
            name="duration",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="resumeeducation",
            name="field_of_study",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="resumeexperience",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="resumeexperience",
            name="duration",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="resumeexperience",
            name="skills_used",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resumeproject",
            name="category",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="resumeproject",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="resumeproject",
            name="duration",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="resumeproject",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="resumeproject",
            name="organization",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="resumeproject",
            name="role",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="resumeproject",
            name="status",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="resumeproject",
            name="team_size",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="resumeproject",
            name="tools_used",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resumeproject",
            name="url",
            field=models.CharField(blank=True, default="", max_length=1024),
        ),
        migrations.AddField(
            model_name="resumeskill",
            name="name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="resume",
            name="status",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("generated", "Generated"),
                    ("enhanced", "Enhanced"),
                ],
                default="uploaded",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ResumeVolunteerExperience",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("organization", models.CharField(blank=True, default="", max_length=255)),
                ("position", models.CharField(blank=True, default="", max_length=255)),
                ("start_date", models.CharField(blank=True, default="", max_length=20)),
                ("end_date", models.CharField(blank=True, max_length=20, null=True)),
                ("current", models.BooleanField(default=False)),
                ("duration", models.CharField(blank=True, default="", max_length=50)),
                ("location", models.CharField(blank=True, default="", max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("achievements", models.JSONField(blank=True, default=list)),
                ("responsibilities", models.JSONField(blank=True, default=list)),
                ("skills_used", models.JSONField(blank=True, default=list)),
                ("hours_per_week", models.CharField(blank=True, default="", max_length=50)),
                ("cause", models.CharField(blank=True, default="", max_length=100)),
                ("url", models.CharField(blank=True, default="", max_length=1024)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_experience",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "db_table": "resume_volunteer_experiences",
            },
        ),
        migrations.CreateModel(
            name="ResumeCertification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("issuer", models.CharField(blank=True, default="", max_length=255)),
                ("date", models.CharField(blank=True, default="", max_length=20)),
                ("credential_id", models.CharField(blank=True, default="", max_length=255)),
                ("url", models.CharField(blank=True, default="", max_length=1024)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="resumes.resume",
                    ),
                ),
            ],
            options={
                "db_table": "resume_certifications",
            },
        ),
    ]
