# Generated by Django 4.2.27 on 2026-01-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0002_rename_currently_resumeeducation_current_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="language",
            field=models.CharField(
                choices=[("en", "English"), ("ru", "Russian"), ("uz", "Uzbek")],
                default="en",
                help_text="Resume language for PDF generation and content",
                max_length=5,
            ),
        ),
    ]
