# Generated by Django 4.2.27 on 2026-01-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0003_resume_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="file",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="file_name",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="file_size",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="language",
        ),
        migrations.RemoveField(
            model_name="resumeexperience",
            name="skills_used",
        ),
        migrations.AddField(
            model_name="resumeexperience",
            name="technologies_used",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="resumeskill",
            name="category",
            field=models.CharField(blank=True, default="other", max_length=50),
        ),
        migrations.AddField(
            model_name="resumeskill",
            name="level",
            field=models.CharField(blank=True, default="Intermediate", max_length=50),
        ),
    ]
