# Generated by Django 4.2.27 on 2026-01-03 13:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0004_remove_resume_content_type_remove_resume_file_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resumeexperience",
            old_name="skill_tags",
            new_name="skills_used",
        ),
        migrations.RemoveField(
            model_name="resumeexperience",
            name="technologies_used",
        ),
    ]
