# Generated by Django 4.2.27 on 2026-01-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0005_rename_skill_tags_resumeexperience_skills_used_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="language",
            field=models.CharField(default="en", max_length=10),
        ),
    ]
