# Generated by Django 4.2.27 on 2026-01-03 16:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0006_resume_language"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resume",
            name="status",
        ),
        migrations.AddField(
            model_name="resume",
            name="origin",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("generated", "Generated"),
                    ("enhanced", "Enhanced"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
