# Generated by Django 4.2.27 on 2026-01-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0007_remove_resume_status_resume_origin"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Profile picture for resume (preferably 4:5 ratio)",
                null=True,
                upload_to="media/resume_profiles/",
            ),
        ),
        migrations.AlterField(
            model_name="resume",
            name="origin",
            field=models.CharField(
                choices=[
                    ("uploaded", "Uploaded"),
                    ("qa_generated", "Generated"),
                    ("enhanced", "Enhanced"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
