# Generated by Django 4.2.27 on 2026-01-03 18:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0008_resume_profile_image_alter_resume_origin"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="resume",
            name="resumes_user_id_4e9b43_idx",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="deleted",
        ),
        migrations.RemoveField(
            model_name="resume",
            name="deleted_at",
        ),
    ]
