# Generated by Django 4.2.29 on 2026-04-01 10:06

from django.db import migrations
import pgvector.django.vector


class Migration(migrations.Migration):
    dependencies = [
        ("resumes", "0009_remove_resume_resumes_user_id_4e9b43_idx_and_more"),
        ("matching", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="embedding",
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1024, null=True),
        ),
    ]
