# Generated by Django 4.2.27 on 2025-12-22 14:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("referrals", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="referralsignup",
            new_name="referral_si_referra_fe48f0_idx",
            old_name="referral_s_referr_idx",
        ),
        migrations.RenameIndex(
            model_name="referralsignup",
            new_name="referral_si_referre_912fa5_idx",
            old_name="referral_s_referr_user_idx",
        ),
    ]
